//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendToManager.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SendToManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Failed to read or write to a file in the directory &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ALERT_DIRECTORY_UNAVAILABLE {
            get {
                return ResourceManager.GetString("ALERT_DIRECTORY_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to put numbers in order? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ASK_ASSIGN_NUMBERS {
            get {
                return ResourceManager.GetString("ASK_ASSIGN_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_ARGUMENTS {
            get {
                return ResourceManager.GetString("COLUMN_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_ICONINDEX {
            get {
                return ResourceManager.GetString("COLUMN_ICONINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Icon Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_ICONPATH {
            get {
                return ResourceManager.GetString("COLUMN_ICONPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_PATH {
            get {
                return ResourceManager.GetString("COLUMN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run as Administrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_RUNASADMIN {
            get {
                return ResourceManager.GetString("COLUMN_RUNASADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Working Directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string COLUMN_WORKINGDIRECTORY {
            get {
                return ResourceManager.GetString("COLUMN_WORKINGDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory does not exist. Do you want to create default inventory? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_YOU_WANT_TO_CREATE_DEFAULT_INVENTORY {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_CREATE_DEFAULT_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to remove these existing files from SendTo folder? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_YOU_WANT_TO_REMOVE_FILES {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_REMOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to remove these existing files from SendTo folder before deploying your inventory? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_YOU_WANT_TO_REMOVE_FILES_BEFORE_DEPLOY {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_REMOVE_FILES_BEFORE_DEPLOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ENTER_INVECTORY_NAME {
            get {
                return ResourceManager.GetString("ENTER_INVECTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to copy files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_COPY_FILES {
            get {
                return ResourceManager.GetString("FAILED_TO_COPY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to move files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_MOVE_FILES {
            get {
                return ResourceManager.GetString("FAILED_TO_MOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to remove files. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_REMOVE_FILES {
            get {
                return ResourceManager.GetString("FAILED_TO_REMOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to save setting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_SAVE_SETTING {
            get {
                return ResourceManager.GetString("FAILED_TO_SAVE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory &quot;{0}&quot; has been successfully deployed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVENTORY_DEPLOYED {
            get {
                return ResourceManager.GetString("INVENTORY_DEPLOYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVENTORY_NAME {
            get {
                return ResourceManager.GetString("INVENTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Inventory &quot;{0}&quot; does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVENTORY_NOT_EXIST {
            get {
                return ResourceManager.GetString("INVENTORY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; does not exist. Refresh List and try again. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SELECTED_FILE_DOESNOT_EXIST_REFRESH_FIRST {
            get {
                return ResourceManager.GetString("SELECTED_FILE_DOESNOT_EXIST_REFRESH_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; already exists. Do you want to override? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHORTCUT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SHORTCUT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to create shortcut. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SHORTCUT_CREATION_FAILED {
            get {
                return ResourceManager.GetString("SHORTCUT_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change File Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_CHANGEFILENAME {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_CHANGEFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Change File Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_CHANGEFILETIME {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_CHANGEFILETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open CommandPrompt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_COMMANDLINE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COMMANDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy File Content に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_COPYFILECONTENT {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COPYFILECONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy First Line of File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_COPYFIRSTLINE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COPYFIRSTLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Make .NET2 Application to Run with .NET4 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_DOTNET4RUNNABLE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_DOTNET4RUNNABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Move to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_MOVETO {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_MOVETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy Path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_PATHTOCLIPBOARD {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_PATHTOCLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename with Regex に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_REGEXFILENAMERENAMER {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_REGEXFILENAMERENAMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rename to Folder Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_RENAMETOFOLDERNAME {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RENAMETOFOLDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run as Administrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_RUNASFILE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RUNASFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run one by one に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_RUNONEBYONE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RUNONEBYONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run with Arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_RUNWITHARGS {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RUNWITHARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Send to Sendto に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_SENDTOSENDER {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_SENDTOSENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Switch3264 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_SWITCH3264 {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_SWITCH3264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TOOL_EXPLANATION_TOUCH {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_TOUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unknow option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNKNOWN_OPTION {
            get {
                return ResourceManager.GetString("UNKNOWN_OPTION", resourceCulture);
            }
        }
    }
}
