//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendToManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SendToManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to read or write to a file in the directory &quot;{0}&quot;..
        /// </summary>
        internal static string ALERT_DIRECTORY_UNAVAILABLE {
            get {
                return ResourceManager.GetString("ALERT_DIRECTORY_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} item(s)?.
        /// </summary>
        internal static string ARE_YOU_SURE_DELETE_FILE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_DELETE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to replace &quot;{0}&quot;?.
        /// </summary>
        internal static string ARE_YOU_SURE_REPLACE_FILE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_REPLACE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to put numbers in order?.
        /// </summary>
        internal static string ASK_ASSIGN_NUMBERS {
            get {
                return ResourceManager.GetString("ASK_ASSIGN_NUMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments.
        /// </summary>
        internal static string COLUMN_ARGUMENTS {
            get {
                return ResourceManager.GetString("COLUMN_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Index.
        /// </summary>
        internal static string COLUMN_ICONINDEX {
            get {
                return ResourceManager.GetString("COLUMN_ICONINDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Path.
        /// </summary>
        internal static string COLUMN_ICONPATH {
            get {
                return ResourceManager.GetString("COLUMN_ICONPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string COLUMN_NAME {
            get {
                return ResourceManager.GetString("COLUMN_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string COLUMN_PATH {
            get {
                return ResourceManager.GetString("COLUMN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string COLUMN_RUNASADMIN {
            get {
                return ResourceManager.GetString("COLUMN_RUNASADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Directory.
        /// </summary>
        internal static string COLUMN_WORKINGDIRECTORY {
            get {
                return ResourceManager.GetString("COLUMN_WORKINGDIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory does not exist. Do you want to create default inventory?.
        /// </summary>
        internal static string DO_YOU_WANT_TO_CREATE_DEFAULT_INVENTORY {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_CREATE_DEFAULT_INVENTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove these existing files from SendTo folder?.
        /// </summary>
        internal static string DO_YOU_WANT_TO_REMOVE_FILES {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_REMOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove these existing files from SendTo folder before deploying your inventory?.
        /// </summary>
        internal static string DO_YOU_WANT_TO_REMOVE_FILES_BEFORE_DEPLOY {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_REMOVE_FILES_BEFORE_DEPLOY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        internal static string ENTER_INVECTORY_NAME {
            get {
                return ResourceManager.GetString("ENTER_INVECTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy files..
        /// </summary>
        internal static string FAILED_TO_COPY_FILES {
            get {
                return ResourceManager.GetString("FAILED_TO_COPY_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move files..
        /// </summary>
        internal static string FAILED_TO_MOVE_FILES {
            get {
                return ResourceManager.GetString("FAILED_TO_MOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove files..
        /// </summary>
        internal static string FAILED_TO_REMOVE_FILES {
            get {
                return ResourceManager.GetString("FAILED_TO_REMOVE_FILES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save setting..
        /// </summary>
        internal static string FAILED_TO_SAVE_SETTING {
            get {
                return ResourceManager.GetString("FAILED_TO_SAVE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory &quot;{0}&quot; has been successfully deployed..
        /// </summary>
        internal static string INVENTORY_DEPLOYED {
            get {
                return ResourceManager.GetString("INVENTORY_DEPLOYED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Name.
        /// </summary>
        internal static string INVENTORY_NAME {
            get {
                return ResourceManager.GetString("INVENTORY_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string INVENTORY_NOT_EXIST {
            get {
                return ResourceManager.GetString("INVENTORY_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; does not exist. Refresh List and try again..
        /// </summary>
        internal static string SELECTED_FILE_DOESNOT_EXIST_REFRESH_FIRST {
            get {
                return ResourceManager.GetString("SELECTED_FILE_DOESNOT_EXIST_REFRESH_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; already exists. Do you want to override?.
        /// </summary>
        internal static string SHORTCUT_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SHORTCUT_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create shortcut..
        /// </summary>
        internal static string SHORTCUT_CREATION_FAILED {
            get {
                return ResourceManager.GetString("SHORTCUT_CREATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change File Name.
        /// </summary>
        internal static string TOOL_EXPLANATION_CHANGEFILENAME {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_CHANGEFILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change File Time.
        /// </summary>
        internal static string TOOL_EXPLANATION_CHANGEFILETIME {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_CHANGEFILETIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open CommandPrompt.
        /// </summary>
        internal static string TOOL_EXPLANATION_COMMANDLINE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COMMANDLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy File Content.
        /// </summary>
        internal static string TOOL_EXPLANATION_COPYFILECONTENT {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COPYFILECONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy First Line of File.
        /// </summary>
        internal static string TOOL_EXPLANATION_COPYFIRSTLINE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COPYFIRSTLINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Path.
        /// </summary>
        internal static string TOOL_EXPLANATION_COPYPATH {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_COPYPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make .NET2 Application to Run with .NET4.
        /// </summary>
        internal static string TOOL_EXPLANATION_DOTNET4RUNNABLE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_DOTNET4RUNNABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to.
        /// </summary>
        internal static string TOOL_EXPLANATION_MOVETO {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_MOVETO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename with Regex.
        /// </summary>
        internal static string TOOL_EXPLANATION_REGEXFILENAMERENAMER {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_REGEXFILENAMERENAMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename to Folder Name.
        /// </summary>
        internal static string TOOL_EXPLANATION_RENAMETOFOLDERNAME {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RENAMETOFOLDERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run as Administrator.
        /// </summary>
        internal static string TOOL_EXPLANATION_RUNASFILE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RUNASFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run one by one.
        /// </summary>
        internal static string TOOL_EXPLANATION_RUNONEBYONE {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RUNONEBYONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run with Arguments.
        /// </summary>
        internal static string TOOL_EXPLANATION_RUNWITHARGS {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_RUNWITHARGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Sendto.
        /// </summary>
        internal static string TOOL_EXPLANATION_SENDTOSENDER {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_SENDTOSENDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch3264.
        /// </summary>
        internal static string TOOL_EXPLANATION_SWITCH3264 {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_SWITCH3264", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch.
        /// </summary>
        internal static string TOOL_EXPLANATION_TOUCH {
            get {
                return ResourceManager.GetString("TOOL_EXPLANATION_TOUCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to handle internet shortcut file..
        /// </summary>
        internal static string UNABLE_TO_HANDLE_INTERNET_SHORTCUT_FILE {
            get {
                return ResourceManager.GetString("UNABLE_TO_HANDLE_INTERNET_SHORTCUT_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow option.
        /// </summary>
        internal static string UNKNOWN_OPTION {
            get {
                return ResourceManager.GetString("UNKNOWN_OPTION", resourceCulture);
            }
        }
    }
}
