//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunOnebyOne.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunOnebyOne.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Administrator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ADMINISTRATOR {
            get {
                return ResourceManager.GetString("ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Are you sure you want to run these commands? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BEFORE_RUN_MESSAGE {
            get {
                return ResourceManager.GetString("BEFORE_RUN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancelling に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CANCELLING_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CANCELLING_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All commands are already finished. Do you want to run them again? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_IT_AGAIN {
            get {
                return ResourceManager.GetString("DO_IT_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DONE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("DONE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This application requires .NET 4.5 or above installed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DOTNET_45_REQUIRED {
            get {
                return ResourceManager.GetString("DOTNET_45_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Pause に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PAUSE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("PAUSE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press OK with Ctrl pressed to go to URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PRESS_CTRL_OK {
            get {
                return ResourceManager.GetString("PRESS_CTRL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process exited with {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROCESS_EXIT_WITH {
            get {
                return ResourceManager.GetString("PROCESS_EXIT_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process is null. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PROCESS_IS_NULL {
            get {
                return ResourceManager.GetString("PROCESS_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Run に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RUN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("RUN_BUTTON_TEXT", resourceCulture);
            }
        }
    }
}
