//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunOnebyOne.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RunOnebyOne.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string ADMINISTRATOR {
            get {
                return ResourceManager.GetString("ADMINISTRATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to run these commands?.
        /// </summary>
        internal static string BEFORE_RUN_MESSAGE {
            get {
                return ResourceManager.GetString("BEFORE_RUN_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Cancel.
        /// </summary>
        internal static string CANCEL_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        internal static string CANCELLING_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("CANCELLING_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The build-in command &apos;{0}&apos; is not executable as it is, Do you wanto to change it to &apos;cmd /c&apos;?.
        /// </summary>
        internal static string CHANGE_BUILDINCOMMAND_TO_CMD {
            get {
                return ResourceManager.GetString("CHANGE_BUILDINCOMMAND_TO_CMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All commands are already finished. Do you want to run them again?.
        /// </summary>
        internal static string DO_IT_AGAIN {
            get {
                return ResourceManager.GetString("DO_IT_AGAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DONE_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("DONE_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application requires .NET 4.5 or above installed..
        /// </summary>
        internal static string DOTNET_45_REQUIRED {
            get {
                return ResourceManager.GetString("DOTNET_45_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save ini file..
        /// </summary>
        internal static string FAILED_TO_SAVE_INI {
            get {
                return ResourceManager.GetString("FAILED_TO_SAVE_INI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press OK with Ctrl pressed to go to URL.
        /// </summary>
        internal static string PRESS_CTRL_OK {
            get {
                return ResourceManager.GetString("PRESS_CTRL_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process exited with {0}..
        /// </summary>
        internal static string PROCESS_EXIT_WITH {
            get {
                return ResourceManager.GetString("PROCESS_EXIT_WITH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process is null..
        /// </summary>
        internal static string PROCESS_IS_NULL {
            get {
                return ResourceManager.GetString("PROCESS_IS_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Run.
        /// </summary>
        internal static string RUN_BUTTON_TEXT {
            get {
                return ResourceManager.GetString("RUN_BUTTON_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear the results?.
        /// </summary>
        internal static string SURE_TO_CLEAR_RESULTS {
            get {
                return ResourceManager.GetString("SURE_TO_CLEAR_RESULTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove all items?.
        /// </summary>
        internal static string SURE_TO_REMOVE_ALL_ITEMS {
            get {
                return ResourceManager.GetString("SURE_TO_REMOVE_ALL_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove {0} items?.
        /// </summary>
        internal static string SURE_TO_REMOVE_COUNT_ITEMS {
            get {
                return ResourceManager.GetString("SURE_TO_REMOVE_COUNT_ITEMS", resourceCulture);
            }
        }
    }
}
