//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeFileName.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeFileName.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to trash &apos;{0}&apos;.
        /// </summary>
        internal static string ARE_YOU_SURE_TO_TRASH {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_TO_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Clear.
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination already has a file named &quot;{0}&quot;. Do you want to replace the file in the destination?.
        /// </summary>
        internal static string DESTINATION_EXISTS {
            get {
                return ResourceManager.GetString("DESTINATION_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Filename.
        /// </summary>
        internal static string ENTER_FILENAME {
            get {
                return ResourceManager.GetString("ENTER_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extention.
        /// </summary>
        internal static string Extention {
            get {
                return ResourceManager.GetString("Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found : {0}.
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following files do not exist..
        /// </summary>
        internal static string FOLLOWING_DOESNOT_EXIST {
            get {
                return ResourceManager.GetString("FOLLOWING_DOESNOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name must not include following letters.
        /// </summary>
        internal static string FOLLOWING_UNABLE_FILENAME {
            get {
                return ResourceManager.GetString("FOLLOWING_UNABLE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChangeFileName.exe file
        ///
        ///Change Filename..
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Folder....
        /// </summary>
        internal static string NEW_FOLDER_DDD {
            get {
                return ResourceManager.GetString("NEW_FOLDER_DDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Arguments.
        /// </summary>
        internal static string NO_ARGUMENTS {
            get {
                return ResourceManager.GetString("NO_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
    }
}
