//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeFileName.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeFileName.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Are you sure to trash &apos;{0}&apos; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ARE_YOU_SURE_TO_TRASH {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE_TO_TRASH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Clear に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The destination already has a file named &quot;{0}&quot;. Do you want to replace the file in the destination? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DESTINATION_EXISTS {
            get {
                return ResourceManager.GetString("DESTINATION_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &quot;{0}&quot; does not exist. Do you want to remove it from menus? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DIR_NOT_EXIST_DO_YOU_WANT_TO_REMOVE {
            get {
                return ResourceManager.GetString("DIR_NOT_EXIST_DO_YOU_WANT_TO_REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please enter Filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ENTER_FILENAME {
            get {
                return ResourceManager.GetString("ENTER_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Extention に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Extention {
            get {
                return ResourceManager.GetString("Extention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load &apos;{0}&apos; 
        ///
        ///Reason:
        ///{1}
        ///
        ///Fix the file and press OK or press Cancel to exit.
        ///If this probrem continues, delete the file but you will lost all information about External Tools. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_LOAD_TOOLXML {
            get {
                return ResourceManager.GetString("FAILED_TO_LOAD_TOOLXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found : {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_NOT_FOUND {
            get {
                return ResourceManager.GetString("FILE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Following files do not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FOLLOWING_DOESNOT_EXIST {
            get {
                return ResourceManager.GetString("FOLLOWING_DOESNOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File name must not include following letters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FOLLOWING_UNABLE_FILENAME {
            get {
                return ResourceManager.GetString("FOLLOWING_UNABLE_FILENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ChangeFileName.exe file
        ///
        ///Change Filename. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HELP {
            get {
                return ResourceManager.GetString("HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;New Folder... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NEW_FOLDER_DDD {
            get {
                return ResourceManager.GetString("NEW_FOLDER_DDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No Arguments に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_ARGUMENTS {
            get {
                return ResourceManager.GetString("NO_ARGUMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;No External Tools registered&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_EXTERNAL_TOOLS_REGISTERED {
            get {
                return ResourceManager.GetString("NO_EXTERNAL_TOOLS_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Not Exists) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOT_EXISTS {
            get {
                return ResourceManager.GetString("NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
    }
}
