//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ambiesoft.RegexFilenameRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ambiesoft.RegexFilenameRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Both /cf and /ncf specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BOTH_CF_NCF_SPECIFIED {
            get {
                return ResourceManager.GetString("BOTH_CF_NCF_SPECIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to continue? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_YOU_WANT_TO_CONTINUE {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_CONTINUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to perform {0} renames? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DO_YOU_WANT_TO_PERFORM_N_RENAME {
            get {
                return ResourceManager.GetString("DO_YOU_WANT_TO_PERFORM_N_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to move &apos;{0}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FAILED_TO_MOVE_S {
            get {
                return ResourceManager.GetString("FAILED_TO_MOVE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; does not exist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If an option value begins with &apos;-&apos;, put &quot;--&quot; before it to treat it as a value. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HYPHEN_EXPLANATION {
            get {
                return ResourceManager.GetString("HYPHEN_EXPLANATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid option: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_OPTION {
            get {
                return ResourceManager.GetString("INVALID_OPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Both /rf and /rt must be specified. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MUST_SPECIFY_RF_RT {
            get {
                return ResourceManager.GetString("MUST_SPECIFY_RF_RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;No Change&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_CHANGE {
            get {
                return ResourceManager.GetString("NO_CHANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_FILE {
            get {
                return ResourceManager.GetString("NO_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No files to rename. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_FILES_TO_RENAME {
            get {
                return ResourceManager.GetString("NO_FILES_TO_RENAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected error. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNEXPECTED_ERROR {
            get {
                return ResourceManager.GetString("UNEXPECTED_ERROR", resourceCulture);
            }
        }
    }
}
